### ISSUE TITLE
Printing in the debugger opens an emergency debugger even if it could open a normal debugger

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#118] opened 2020-10-09 09:05 UTC
I'm in a debugger
I write some code on it.
I evaluate it.
The expression raises some exception (e.g., DNU).
Instead of opening a new debugger session for my *doIt* and opening it in a new debugger, I have an emergency debugger.

**Comment by MarcusDenker** [comment] 2020-10-09 09:11
This happens, too, in an inspector that you open from the debugger: just inspect something (e.g. self) and put a "self halt" in the eval pane of the inspector--> Emergency debugger

**Comment by StevenCostiou** [comment] 2020-10-12 11:16
I do not have this problem, let's wait for the next newtool merge and check if it still reproduces.

**Comment by guillep** [comment] 2020-10-12 11:17
This can be reproduced in a vanilla Pharo9 image.

**Comment by guillep** [comment] 2020-10-12 11:19
So confirming you can reproduce it in a vanilla pharo image without latest newtools, and not in the one with latest new tools gives an idea if it is working or not, if it is dependent on your machine or some other configuration or not...

Myself I don't use any special configuration

**Comment by StevenCostiou** [comment] 2020-11-09 07:25
Is this still a problem?

**Comment by StevenCostiou** [comment] 2020-11-09 07:30
I cannot reproduce, so I'm closing it.

**Closed by StevenCostiou** 2020-11-09 07:30 UTC
