### ISSUE TITLE
Playground does not let execute code

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#221] opened 2021-04-27 08:30 UTC
![Screenshot 2021-04-27 at 10 16 17](https://user-images.githubusercontent.com/432549/116210859-8a4ece80-a743-11eb-9bcd-bf1fa73e15d4.png)
![Screenshot 2021-04-27 at 10 22 33](https://user-images.githubusercontent.com/432549/116210883-8fac1900-a743-11eb-94e3-f4c31a20cc26.png)

**Comment by Ducasse** [comment] 2021-04-27 08:30
Name already defined is totally obscure. 
The bindings looks correct. 
No clue what to do.

**Comment by MarcusDenker** [comment] 2021-04-28 07:02
can you copy the test? The dialog now obscures the variable name...

**Comment by Ducasse** [comment] 2021-04-28 08:08
I cannot execute a doit. 
I cannot execute the expression. 
I just get this pop up and the only thing I can do is to close that playground and open a new one. 
I ended up using the old GT.

**Comment by Ducasse** [comment] 2021-04-28 08:10
The expression was fully working in another playground.

**Comment by Ducasse** [comment] 2021-04-28 08:26
I rescue one of the similar expressions we use.

```
| pillarParser writer doc d t directory file browser rootTopic |

pillarParser := PRPillarParser new.
writer := PRMicrodownWriter new.
doc := pillarParser parse: (FileSystem workingDirectory / 'withStylemini.pillar') contents.
d := writer start: doc; contents.

directory :=  FileSystem disk workingDirectory / 'withStylemini.md'.
file writeStreamDo: [ :st | st nextPutAll: d ].


browser := SpNewHelpBrowserPresenter new.
rootTopic := (browser topicsFromSystem: directory) rootTopic.
SpNewHelpBrowserPresenter openOn: rootTopic
```

**Comment by MarcusDenker** [comment] 2021-04-28 08:27
This seems to happen if there you define a temp with the same name as an existing workspace binding.

This is not correct: the defined temps should shadow the workspace binding.

I will have a look what goes wrong

**Comment by Ducasse** [comment] 2021-04-28 08:28
I do not know but as a user we are trapped and we cannot do anything.

**Comment by MarcusDenker** [comment] 2021-04-28 08:29
There is a related fix in the queue: https://github.com/pharo-spec/NewTools/pull/215 

This will at least reduce the amount (that is, avoid) of bindings created during normal debugger use.

**Comment by Ducasse** [comment] 2021-04-28 08:30
So with the playground I happen to just lose code and time. 
I prefer an old workspace that does not save the code because at least I know that I cannot trust it. 
I prefer no expectation and a working behavior than a supposely working not broken system. 
Yesterday I bump from bug to bug. It was tiring.

**Comment by MarcusDenker** [comment] 2021-04-28 08:31
I do not know how to do things without sometimes doing things wrong. And "but there should be tests" is not always the solution as often the problem is that I did not even know that I should have tested exactly that....

**Comment by Ducasse** [comment] 2021-04-28 08:38
The point is not not doing something wrong. 
The point is limiting the impact on others. 
This is not normal that we decided not to use Pharo 90 latest for the VM. 
We cannot continuously fix or face bugs. 
I think that either 
- we push fast and fix fast (but who is checking)
- we work a bit slower in a branch and are our first tested. 

I favor the second version. I did around 40 commits in my repo before pushing 
the change of the printer. Like that I do not expose everybody to the obvious bugs that I could see. 
And when it is ready I push to others and of course there are some scenario I did not thought about. 

I did the same for the comment rendering. 
We did the same with the symbol extraction, parser...
Pretty printer and it is working. 

Look the new spotter is not working well and guille and pablo pushed a lot of issues

**Comment by Ducasse** [comment] 2021-04-28 08:43
The tests are important for the fix. 
Of course we cannot have tests up front all the time, but covering tests after this is key to build non regression. 
Yes I found a bug in Pillar that was in the Pillar parser. Took me some times to find it and I covered with several tests. 
Same for Semantic Action in the renderer. Now I should do a release for Pharo and I do not have the energy but I wrote 7 new tests covering the bugs so they will not pop up without being noticed.

**Comment by MarcusDenker** [comment] 2021-04-28 08:44
But will we catch exactly these kind of bugs by delaying the use and have just one person use the code?

**Comment by Ducasse** [comment] 2021-04-28 09:07
I will start not using bleeding edge anymore (It also means that I will fix also less Pharo).
Guille and Pablo are doing the same because when you are working in the VM you want to focus on your own bugs. 
The point is what is our productivity and how much are we ready to damage it. 
The system is in regression from that perspective. 
Mainly also because Calypso is super difficult to test. 
But let us look at it, there is not a SINGLE decent test for the Playground. 
I cannot even ask a student to improve them nor to write tests for the new help browser because Spec20 does not offer the API to support tests. I tried and immediately bumped into a bug. What is the message?
We do not care about your tests. Ok fair enough. So in that case I redraw and we will not write tests and do something else. 
We will work on the help browser but after that we stop. Period.
I will not continue like that.

**Comment by MarcusDenker** [comment] 2021-04-28 10:37
I analyzed the problem:

to solve #215, I changed #lookupVarForDeclaration: to no skip the requestor scope, but to instead just not create new bindings.

This now has the side-effect that we get an error for when a variable declaration shadows a variable defined by the requestor.

We could fix this by making the requestor variable special and allow them to be shadowed without raising an error

```
declareVariableNode: aVariableNode as: anOCTempVariable
	| name var shadowing |
	name := aVariableNode name. 
	var := scope lookupVarForDeclaration: name.
	"check if another variable with same name is visible"
	var ifNotNil: [ shadowing := var].
	var := scope addTemp: anOCTempVariable.
	aVariableNode binding: var.
	"we allow shadowing of variables defined by the playground"
	(shadowing notNil and: [ shadowing isWorkspaceVariable not ]) ifTrue: [self shadowingVariable: aVariableNode].
	^ var
```

This is kind of a hack because it tests especially for WorkspaceVariable. On the other hand it makes explicit what we did ready before by accident. 

We could have a method #allwaysAllowShowing on Variable that is true for Workspace variables and check for that, instead of hardcoding it here.

**Comment by MarcusDenker** [comment] 2021-05-12 07:38
this has been merged

**Closed by MarcusDenker** 2021-05-12 07:38 UTC
