### ISSUE TITLE
#senders printString -> DNU

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/NewTools#258] opened 2021-07-03 14:57 UTC
![Screenshot 2021-07-03 at 16 56 46](https://user-images.githubusercontent.com/432549/124358251-c01aa280-dc1f-11eb-810a-920054cc3764.png)

**Comment by Ducasse** [comment] 2021-07-03 15:01
![Screenshot 2021-07-03 at 17 00 43](https://user-images.githubusercontent.com/432549/124358363-3a4b2700-dc20-11eb-9a8d-9c7b61d80dc1.png)

**Comment by Ducasse** [comment] 2021-07-03 15:01
It looks like there is something broken using #stuff....

**Comment by estebanlm** [comment] 2021-07-05 12:16
Last changes I introduced (to be integrated to the image later today) seems to have fixed this (or at least, I can't reproduce it). 
I made some tweaks because I was also having problems... I was not sure (and I still not sure) I fixed all the problems, but seems to be better .
In any case, let me know if after this update this problem remains.

**Comment by MarcusDenker** [comment] 2021-09-16 13:29
This is fixed in the latest version, I just tried it.

**Closed as completed by MarcusDenker** 2021-09-16 13:29 UTC
