### ISSUE TITLE
"Copy stack to clipboard" doesn't copy the whole stack

### ISSUE THREAD

**Issue by ValentinBourcier** [pharo-spec/NewTools#441] opened 2022-11-25 08:41 UTC
Original issue: https://github.com/pharo-project/pharo/issues/11973

Describe the request

The functionality "Copy stack to clipboard" accessible from the right click contextual menu when hovering a stack is not copying the whole stack.

Expected behavior

As it was reported by Éric Le Pors and Pierre Laborde (from Thales), the user expects the whole stack to be copied.

Observations + Expected development cost

According to the tooltip on the menu, it is voluntary to copy only a part of the stack.
By looking in the code, we can observe that only the first 30 elements can be copied to the clipboard.

As it seems not possible to select exactly what to copy, nor to copy the stack entirely, some of the information that the user wants to extract may be missing. This limit is therefore irrelevant and has to be deleted.

Time estimated: less than an hour.

Version information:

    OS: MacOS
    Version: 12.2.1
    Pharo Version: 11

**Comment by MarcusDenker** [comment] 2022-12-06 09:36
We merged https://github.com/pharo-spec/NewTools/pull/442

**Comment by MarcusDenker** [comment] 2022-12-06 09:39
We merged both

- https://github.com/pharo-project/pharo/pull/11983
- https://github.com/pharo-spec/NewTools/pull/442

What needs to be done?

I tried it now in the lastest image, and it copies almost nothing, like 20 lines.

So something still needs to be done

**Comment by StevenCostiou** [comment] 2023-02-10 22:35
Duplicate of https://github.com/pharo-spec/NewTools/issues/217 => both issues should be closed once the problem is resolved.

**Comment by adri09070** [comment] 2023-02-24 14:16
I just tried and I don't see any problem? 

Do you have an example with which I could reproduce the error?

I tried with this example: 

```Smalltalk
MyClassA>>#initialize

	super initialize.
	a := 0
```

```Smalltalk
MyClassA>>#foo
	a >= 100 ifTrue: [
		1 halt.
		^ a ].
	a := a + 1.
	self foo
```

and in a playground: DoIt on 

```Smalltalk
MyClassA new foo
```

So it stops on the halt and I copy the stack to clipboard and I get the entire stack, with more than 100 lines.

**Comment by guillep** [comment] 2023-02-24 14:19
I don't know what is the origin of the issue, but it may be related to some limits like in:

```smalltalk
contextStack 
	"Answer an Array of the contexts on the receiver's sender chain."

	^self stackOfSize: 100000
```

**Comment by adri09070** [comment] 2023-02-24 14:28
Maybe, but @MarcusDenker says he has only 20 lines. This is intriguing.

I saw that there is also a limit of 50000 characters for a clipboard entry. But, it is not possible to reach it with 20 lines, knowing that there is also a limit of 50 characters per context

**Comment by MarcusDenker** [comment] 2023-02-24 15:01
I did cmd . and then do the copy to clipboard, and I get this:

```
[delaySemaphore wait] in Delay>>wait in Block: [delaySemaphore wait]
FullBlockClosure(BlockClosure)>>ifCurtailed:
Delay>>wait
WorldState class>>doInterCycleWait
[
		self doInterCycleWait
	] in WorldState class>>doDrawCycleWith: in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
WorldState class>>doDrawCycleWith:
WorldMorph class>>doOneCycle
MorphicRenderLoop>>doOneCycle
MorphicRenderLoop>>doOneCycleWhile:
[
		MorphicRenderLoop new doOneCycleWhile: [ true ]
	] in MorphicUIManager>>spawnNewProcess in Block: [...
[self value.
			"IMPORTANT: Do not step over next line of code. See method comments for details"
			Processor terminateRealActive] in FullBlockClosure(BlockClosure)>>newProcess in Block: [self value....
``

**Comment by adri09070** [comment] 2023-03-01 14:29
I tried and I'm not even able to stop any process with `CMD + .` . This shortcut  is supposed to stop an infinite loop, right ?

I tried to copy a stack of more than 50000 characters, as I thought that it was the limit for a clipboard entry. But it still works for me.

Where do you try to paste the stack? I paste it in a playground

**Comment by MarcusDenker** [comment] 2023-03-02 15:16
I think I got confused by the ..., but that is done for the source always.

So it works, I close the issue

**Closed as completed by MarcusDenker** 2023-03-02 15:16 UTC
Labels: bug, debugger
