### ISSUE TITLE
Cannot see instance variables in the debugger

### ISSUE THREAD

**Issue by guillep** [pharo-spec/NewTools#89] opened 2020-08-07 21:15 UTC
Pharo-9.0.0+build.580.sha.9514baad3830e43a539d94c24719b0317623995e (64 Bit)

In the bottom inspector I cannot manage to see instance variables:

![image](https://user-images.githubusercontent.com/708322/89689053-d337cc00-d903-11ea-8b0f-8336224fc74f.png)

**Comment by StevenCostiou** [comment] 2020-08-07 22:47
Normally after you select `self` it opens the inspector on the right column and there you should see the inst vars.
Seems wrong from what I can see in your screenshot, as the right column starts by "aBy..." while it seems not to be your object :/

**Comment by StevenCostiou** [comment] 2020-08-12 05:39
Is it working better?
I cannot reproduce that one. I always see the instance variables on the right column after clicking on `self`.
Sometimes though, I have to double click but that is a spec problem.

**Comment by StevenCostiou** [comment] 2020-09-17 16:49
Fixed by https://github.com/pharo-project/pharo/pull/7311

**Closed by StevenCostiou** 2020-09-17 16:49 UTC
