### ISSUE TITLE
StPharoApplication keeps a reference to all the open debuggers

### ISSUE THREAD

**Issue by tesonep** [pharo-spec/NewTools#77] opened 2020-07-21 14:54 UTC
The windows are never released, so the debuggers are kept and the objects with them

**Comment by estebanlm** [comment] 2020-07-24 07:57
but this seems to be a problem on the debugger, something is interfering with the proper release of the windows (I couldn't reproduce it other than with debuggers... but it can be something else too)

**Comment by StevenCostiou** [comment] 2020-07-24 08:06
Ok I'll look at it

**Comment by StevenCostiou** [comment] 2020-07-29 14:01
It's when we proceed the debugger. When you just close it there is no problem.
Proceeding calls `self withWindowDo: #close` is that not sufficient?

**Comment by estebanlm** [comment] 2020-07-30 08:25
I commit a fix to this (it was not *just* debugger related after all ;). 
It should not happen anymore but I need a confirmation.

**Comment by StevenCostiou** [comment] 2020-08-06 12:06
Is this fixed?

**Comment by estebanlm** [comment] 2020-08-09 07:15
I think so

**Comment by StevenCostiou** [comment] 2020-08-12 05:35
After opening a debugger, closing it, there are still windows in the application, doing:
```Smalltalk
StPharoApplication current windows anySatisfy: [ :w| w presenter class = StDebugger ]
```

**Comment by StevenCostiou** [comment] 2020-11-09 07:50
Fixed by https://github.com/pharo-spec/NewTools/pull/127

**Closed by StevenCostiou** 2020-11-09 07:50 UTC
Labels: bug
